services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-filament-app
    container_name: laravel-filament-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    networks:
      - laravel-filament

  db:
    image: mysql:8.0
    container_name: laravel-filament-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-filament

  node:
    image: node:20.11.1
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["npm", "install"]
    networks:
      - laravel-filament

networks:
  laravel-filament:
    driver: bridge

volumes:
  dbdata:
    driver: local
